/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDisplayData: typeof import('./src/components/AppDisplayData.vue')['default']
    AppLink: typeof import('./src/components/AppLink.vue')['default']
    AppPage: typeof import('./src/components/AppPage.vue')['default']
    AppRGB: typeof import('./src/components/AppRGB.vue')['default']
    IconTonConnect: typeof import('./src/components/IconTonConnect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
